create table if not exists public.expert_invites (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text not null,
  specialty text not null,
  location text not null,
  link text,
  message text not null,
  status text not null default 'new',
  admin_memo text,
  created_at timestamptz not null default now(),
  constraint expert_invites_status_check
    check (status in ('new', 'contacted', 'invited', 'registered'))
);

create index if not exists expert_invites_created_at_idx
on public.expert_invites (created_at desc);

create index if not exists expert_invites_status_idx
on public.expert_invites (status);

alter table public.expert_invites enable row level security;

drop policy if exists "Anyone can request expert invite" on public.expert_invites;
drop policy if exists "Admins can read expert invites" on public.expert_invites;
drop policy if exists "Admins can update expert invites" on public.expert_invites;

create policy "Anyone can request expert invite"
on public.expert_invites
for insert
to anon, authenticated
with check (true);

create policy "Admins can read expert invites"
on public.expert_invites
for select
to authenticated
using (public.is_admin());

create policy "Admins can update expert invites"
on public.expert_invites
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());
