create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  expert_id bigint not null references public.experts(id) on delete cascade,
  user_id uuid references auth.users(id) on delete set null,
  rating integer not null check (rating between 1 and 5),
  content text not null,
  created_at timestamptz not null default now()
);

create index if not exists reviews_expert_id_idx
on public.reviews (expert_id);

create index if not exists reviews_user_id_idx
on public.reviews (user_id);

create index if not exists reviews_created_at_idx
on public.reviews (created_at desc);

alter table public.reviews enable row level security;

drop policy if exists "Public can read reviews" on public.reviews;
drop policy if exists "Authenticated users can create reviews" on public.reviews;
drop policy if exists "Users can delete own reviews" on public.reviews;
drop policy if exists "Admins can manage reviews" on public.reviews;

create policy "Public can read reviews"
on public.reviews
for select
to anon, authenticated
using (true);

create policy "Authenticated users can create reviews"
on public.reviews
for insert
to authenticated
with check (auth.uid() = user_id);

create policy "Users can delete own reviews"
on public.reviews
for delete
to authenticated
using (auth.uid() = user_id);

create policy "Admins can manage reviews"
on public.reviews
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());
