create table if not exists public.feedback (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  nickname text not null,
  purpose text not null,
  satisfaction integer not null check (satisfaction between 1 and 5),
  liked text not null,
  pain_point text not null,
  improvement_idea text not null,
  reuse_intent text not null check (reuse_intent in ('있음', '없음', '모르겠음')),
  created_at timestamptz not null default now()
);

create index if not exists feedback_created_at_idx
on public.feedback (created_at desc);

create index if not exists feedback_purpose_idx
on public.feedback (purpose);

create index if not exists feedback_satisfaction_idx
on public.feedback (satisfaction);

alter table public.feedback enable row level security;

drop policy if exists "Anyone can create feedback" on public.feedback;
drop policy if exists "Admins can read feedback" on public.feedback;
drop policy if exists "Admins can delete feedback" on public.feedback;

create policy "Anyone can create feedback"
on public.feedback
for insert
to anon, authenticated
with check (true);

create policy "Admins can read feedback"
on public.feedback
for select
to authenticated
using (public.is_admin());

create policy "Admins can delete feedback"
on public.feedback
for delete
to authenticated
using (public.is_admin());
