create table if not exists public.premium_plan_requests (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  requester_name text,
  requester_email text,
  source_page text not null default '/pricing',
  status text not null default 'pending'
    check (status in ('pending', 'contacted', 'approved', 'rejected')),
  created_at timestamptz not null default now()
);

create index if not exists premium_plan_requests_created_at_idx
on public.premium_plan_requests (created_at desc);

create index if not exists premium_plan_requests_status_idx
on public.premium_plan_requests (status);

alter table public.premium_plan_requests enable row level security;

drop policy if exists "Anyone can create premium plan requests"
on public.premium_plan_requests;
drop policy if exists "Admins can read premium plan requests"
on public.premium_plan_requests;
drop policy if exists "Admins can update premium plan requests"
on public.premium_plan_requests;

create policy "Anyone can create premium plan requests"
on public.premium_plan_requests
for insert
to anon, authenticated
with check (true);

create policy "Admins can read premium plan requests"
on public.premium_plan_requests
for select
to authenticated
using (public.is_admin());

create policy "Admins can update premium plan requests"
on public.premium_plan_requests
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());
