create table if not exists public.favorites (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  expert_id bigint not null references public.experts(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (user_id, expert_id)
);

create index if not exists favorites_user_id_idx
on public.favorites (user_id);

create index if not exists favorites_expert_id_idx
on public.favorites (expert_id);

alter table public.favorites enable row level security;

drop policy if exists "Users can read own favorites" on public.favorites;
drop policy if exists "Users can create own favorites" on public.favorites;
drop policy if exists "Users can delete own favorites" on public.favorites;
drop policy if exists "Admins can read all favorites" on public.favorites;

create policy "Users can read own favorites"
on public.favorites
for select
to authenticated
using (auth.uid() = user_id);

create policy "Users can create own favorites"
on public.favorites
for insert
to authenticated
with check (auth.uid() = user_id);

create policy "Users can delete own favorites"
on public.favorites
for delete
to authenticated
using (auth.uid() = user_id);

create policy "Admins can read all favorites"
on public.favorites
for select
to authenticated
using (public.is_admin());
