create table if not exists public.consultation_requests (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  customer_name text not null,
  customer_email text not null,
  customer_phone text not null,
  category text not null,
  message text not null,
  expert_id bigint references public.experts(id) on delete set null,
  status text not null default 'pending'
    check (status in ('pending', 'accepted', 'rejected', 'completed'))
);

create index if not exists consultation_requests_created_at_idx
on public.consultation_requests (created_at desc);

create index if not exists consultation_requests_expert_id_idx
on public.consultation_requests (expert_id);

create index if not exists consultation_requests_status_idx
on public.consultation_requests (status);

alter table public.consultation_requests enable row level security;

drop policy if exists "Anyone can create consultation requests"
on public.consultation_requests;
drop policy if exists "Admins can read consultation requests"
on public.consultation_requests;
drop policy if exists "Admins can update consultation requests"
on public.consultation_requests;
drop policy if exists "Experts can read own consultation requests"
on public.consultation_requests;
drop policy if exists "Experts can update own consultation requests"
on public.consultation_requests;

create policy "Anyone can create consultation requests"
on public.consultation_requests
for insert
to anon, authenticated
with check (true);

create policy "Admins can read consultation requests"
on public.consultation_requests
for select
to authenticated
using (public.is_admin());

create policy "Admins can update consultation requests"
on public.consultation_requests
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "Experts can read own consultation requests"
on public.consultation_requests
for select
to authenticated
using (
  exists (
    select 1
    from public.experts
    where experts.id = consultation_requests.expert_id
      and experts.user_id = auth.uid()
  )
);

create policy "Experts can update own consultation requests"
on public.consultation_requests
for update
to authenticated
using (
  exists (
    select 1
    from public.experts
    where experts.id = consultation_requests.expert_id
      and experts.user_id = auth.uid()
  )
)
with check (
  exists (
    select 1
    from public.experts
    where experts.id = consultation_requests.expert_id
      and experts.user_id = auth.uid()
  )
);
