create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  event_name text not null,
  page text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists analytics_events_event_name_idx
on public.analytics_events (event_name);

create index if not exists analytics_events_created_at_idx
on public.analytics_events (created_at desc);

create index if not exists analytics_events_page_idx
on public.analytics_events (page);

alter table public.analytics_events enable row level security;

drop policy if exists "Anyone can create analytics events" on public.analytics_events;
drop policy if exists "Admins can read analytics events" on public.analytics_events;

create policy "Anyone can create analytics events"
on public.analytics_events
for insert
to anon, authenticated
with check (true);

create policy "Admins can read analytics events"
on public.analytics_events
for select
to authenticated
using (public.is_admin());
