create table if not exists public.premium_requests (
  id bigint generated by default as identity primary key,
  expert_id bigint references public.experts(id) on delete set null,
  user_id uuid references auth.users(id) on delete set null,
  name text not null,
  email text not null,
  phone text not null,
  message text not null,
  status text not null default 'pending'
    check (status in ('pending', 'approved', 'rejected')),
  created_at timestamptz not null default now()
);

create index if not exists premium_requests_created_at_idx
on public.premium_requests (created_at desc);

create index if not exists premium_requests_status_idx
on public.premium_requests (status);

create index if not exists premium_requests_expert_id_idx
on public.premium_requests (expert_id);

alter table public.premium_requests enable row level security;

drop policy if exists "Anyone can create premium requests"
on public.premium_requests;
drop policy if exists "Admins can read premium requests"
on public.premium_requests;
drop policy if exists "Admins can update premium requests"
on public.premium_requests;

create policy "Anyone can create premium requests"
on public.premium_requests
for insert
to anon, authenticated
with check (true);

create policy "Admins can read premium requests"
on public.premium_requests
for select
to authenticated
using (public.is_admin());

create policy "Admins can update premium requests"
on public.premium_requests
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());
